name: 'Changelog generator for the Github release'
description: 'Github action that generaters a changelog und create a release in Github.'
author: 'andrejpetras'
branding:
  icon: edit
  color: blue
runs:
  using: "docker"
  image: "docker://ghcr.io/lorislab/changelog:1.5.0"
